
---
version: '3.4'
services:
  weaviate:

    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    links:
      - "contextionary:contextionary"
    ports:
    - 8080:8080
    - 50051:50051
    restart: on-failure:0
    env_file: .env
    environment:
      LOG_LEVEL: "debug"
      CONTEXTIONARY_URL: contextionary:9999
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      ENABLE_MODULES: text2vec-transformers,text2vec-contextionary,backup-filesystem,generative-openai,text2vec-openai
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      BACKUP_FILESYSTEM_PATH: "/tmp/backups"
      CLUSTER_GOSSIP_BIND_PORT: "7100"
      CLUSTER_DATA_BIND_PORT: "7101"
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: "OPENAI_API_KEY"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/v1" ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 5s
  t2v-transformers:
    image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: 0 # set to 1 to enable
      # NVIDIA_VISIBLE_DEVICES: all # enable if running with CUDA
  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.2.0
    environment:
      LOG_LEVEL: "debug"
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8080
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
